#cloud-config

write_files:
  - path: /etc/docker/daemon.json
    permissions: 0644
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {"max-size": "10m", "max-file": "5"}
      }
  - path: /root/join-cluster.sh
    permissions: 0755
    content: |
      #!/bin/bash
      mkdir -p /mnt/scratch && chmod a+w+x /mnt/scratch
      HOSTNAME=`hostname`
      # get the  cluster token
      TOKEN=$(wget -nv -q -O - --retry-connrefused --tries=0 --waitretry 5 http://master0:1337/join/$HOSTNAME)
      # install k3s and join the cluster
      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$K3S_VERSION K3S_URL=https://master0:6443 K3S_TOKEN=$TOKEN sh -
  - path: /root/leave-cluster.sh
    permissions: 0755
    content: |
      #!/bin/bash
      HOSTNAME=`hostname`
      # signal the master to drain services from our node
      wget -nv -q -O - --retry-connrefused --tries=10 --waitretry 5 http://master0:1337/drain/$HOSTNAME
  - path: /root/spot-helper.py
    permissions: 0755
    content: |
      #!/usr/bin/env python3

      # Leave the cluster in an orderly fashion when the spot instance is preempted or scheduled for maintenance

      from subprocess import check_output
      from socket import gethostname
      from time import sleep
      from json import loads
      from urllib.request import Request, urlopen
      from urllib.parse import urlencode

      METADATA_URL = "http://169.254.169.254/metadata/scheduledevents?api-version=2017-11-01"
      
      def get_scheduled_events():
          req = Request(METADATA_URL)
          req.add_header('Metadata', 'true')
          res = urlopen(req)
          data = loads(res.read())
          return data

      def acknowledge_event(event_id):
          req = Request(METADATA_URL, urlencode({"StartRequests":[{"EventId":event_id}]}))
          req.add_header('Metadata', 'true')
          res = urlopen(req)
          data = res.read()
          return data

      def handle_events(data):
          hostname = gethostname()
          for event in data['Events']:
              if hostname in event['Resources'] and event['EventType'] in ['Reboot', 'Redeploy', 'Preempt']:
                  check_output('/root/leave-cluster.sh', shell=True)
                  acknowledge_event(event['EventId'])

      if __name__ == '__main__':
          while(True):
             sleep(15)
             handle_events(get_scheduled_events())
  - path: /etc/systemd/system/spot-helper.service
    permissions: 0444
    content: |
      [Unit]
      Description=Azure Spot Instance Events
      DefaultDependencies=no
      After=multi-user.target
      [Service]
      Type=oneshot
      ExecStart=/root/spot-helper.py
      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/k3s-join.service
    permissions: 0444
    content: |
      [Unit]
      Description=Join k3s cluster
      DefaultDependencies=no
      After=multi-user.target
      [Service]
      Type=oneshot
      ExecStart=/root/join-cluster.sh
      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/k3s-leave.service
    permissions: 0444
    content: |
      [Unit]
      Description=Leave k3s cluster
      DefaultDependencies=no
      Before=shutdown.target reboot.target halt.target
      [Service]
      Type=oneshot
      ExecStart=/root/leave-cluster.sh
      [Install]
      WantedBy=halt.target reboot.target shutdown.target
  - path: /etc/waagent.conf
    permissions: 0444
    content: |
      ResourceDisk.Format=y
      ResourceDisk.Filesystem=ext4
      ResourceDisk.EnableSwap=y
      ResourceDisk.SwapSizeMB=2048
  - path: /etc/rancher/k3s/registries.yaml
    permissions: 0444
    content: |
      mirrors:
        "master0:5000":
          endpoint:
            - http://master0:5000 

mounts:
  - - //${STORAGE_ACCOUNT_NAME}.file.core.windows.net/${SHARE_NAME}
    - /srv
    - cifs
    - vers=3.0,username=${STORAGE_ACCOUNT_NAME},password=${STORAGE_ACCOUNT_KEY},dir_mode=0770,file_mode=0660,uid=1000,gid=1000,noperm,noatime,mfsymlinks,iocharset=utf8

apt:
  package_update: true
  package_upgrade: true
packages:
  - ntp
  #- tmux
  #- htop
  #- vim
  - fail2ban
  #- curl
  - docker.io

runcmd:
  - timedatectl set-timezone Europe/Lisbon
  - systemctl enable k3s-join
  - systemctl enable k3s-leave
  - systemctl enable spot-helper
  #- systemctl start k3s-leave
  #- systemctl start k3s-join
  # remove snapd so it doesn't cause extra load on smaller VMs
  - apt-get purge -y snapd unattended-upgrades
  - rm -rf /snap /var/snap /var/lib/snapd /var/log/unattended-upgrades
  - apt-get dist-upgrade -y
  - apt-get autoremove -y
  - reboot
