#cloud-config

write_files:
  - path: /etc/ssh/sshd_config
    append: true
    content: |
      Port 2211
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
  - path: /etc/rancher/k3s/config.yaml
    permissions: 0644
    content: |
      write-kubeconfig-mode: "0644"
  - path: /etc/docker/daemon.json
    permissions: 0644
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {"max-size": "10m", "max-file": "5"}
      }
  - path: /root/k3s-helper.py
    permissions: 0755
    content: |
      #!/usr/bin/env python3
      from bottle import get, run, abort
      from subprocess import check_output
      from socket import gethostname
      from signal import signal, setitimer, ITIMER_REAL, SIGALRM
      from sys import stderr

      def cleanup(signum, frame):
          if signum in [9, 15]:
            stderr.write(f"Exiting on signal {signum}\n")
            exit(0)
          try:
              nodes = check_output('kubectl get nodes', shell=True).strip().decode("utf-8")
              untagged = map(lambda x: x.split()[0], filter(lambda x: '<none>' in x, nodes.split('\n')))
              down = map(lambda x: x.split()[0], filter(lambda x: 'NotReady' in x, nodes.split('\n')))
              for node in untagged:
                  check_output(f"kubectl label node {node} kubernetes.io/role=worker", shell=True)
              for node in down:
                  check_output(f"kubectl cordon {node}", shell=True)
                  check_output(f"kubectl delete node {node}", shell=True)
          except Exception as e:
              stderr.write(f"{e}\n")
              pass

      @get("/join/<hostname>")
      def token(hostname):
          try:
              check_output(f"kubectl uncordon {hostname}", shell=True)
          except:
              pass
          return check_output("cat /var/lib/rancher/k3s/server/node-token", shell=True).strip()
      
      @get("/drain/<hostname>")
      def drain(hostname):
          try:
              check_output(f"kubectl drain {hostname} --ignore-daemonsets --delete-local-data", shell=True)
              return check_output(f"kubectl cordon {hostname}", shell=True).strip()
          except:
              abort(404, "node not found")
        
      if gethostname() == 'master0':
          signal(SIGALRM, cleanup)
          setitimer(ITIMER_REAL, 60, 10)
          run(port=1337,host='0.0.0.0')
  - path: /etc/systemd/system/k3s-helper.service
    permissions: 0444
    content: |
      [Unit]
      Description=k3s Helper
      DefaultDependencies=no
      After=multi-user.target
      [Service]
      Type=oneshot
      ExecStart=/root/k3s-helper.py
      [Install]
      WantedBy=multi-user.target
  - path: /etc/waagent.conf
    permissions: 0444
    content: |
      ResourceDisk.Format=y
      ResourceDisk.Filesystem=ext4
      ResourceDisk.EnableSwap=y
      ResourceDisk.SwapSizeMB=2048
  - path: /etc/rancher/k3s/registries.yaml
    permissions: 0444
    content: |
      mirrors:
        #docker.io:
        #  endpoint:
        #   - https://registry-1.docker.io
        private:
          endpoint:
            - http://master0:5000 
    # If you change the SSH port, don't forget to edit this accordingly
    - path: /etc/fail2ban/jail.d/defaults-debian.conf
      content: |
        [sshd]
        enabled = true
        port = 2211

mounts:
  - - //${STORAGE_ACCOUNT_NAME}.file.core.windows.net/${SHARE_NAME}
    - /srv
    - cifs
    - vers=3.0,username=${STORAGE_ACCOUNT_NAME},password=${STORAGE_ACCOUNT_KEY},dir_mode=0770,file_mode=0660,uid=1000,gid=1000,noperm,mfsymlinks,iocharset=utf8

apt:
  package_update: true
  package_upgrade: true
packages:
  - ntp
  - tmux
  - htop
  - vim
  - fail2ban
  - curl
  - python3-bottle
  - docker.io

runcmd:
  - timedatectl set-timezone Europe/Lisbon
  - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.22.3+k3s1 sh -
  - kubectl completion bash | tee /etc/bash_completion.d/kubectl
  - systemctl enable k3s-helper
  # remove snapd so it doesn't cause extra load on smaller VMs
  - apt-get purge -y snapd unattended-upgrades
  - rm -rf /snap /var/snap /var/lib/snapd /var/log/unattended-upgrades
  - apt-get dist-upgrade -y
  - apt-get autoremove -y
  - reboot
